language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4snapshot'

matrix:
  allow_failures:
    - php: '7.4snapshot'

before_script:
    - composer self-update
    - composer install

script: vendor/bin/phpunit --coverage-clover clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover
